"""Local web demo for multimodal 3D asset quality inspection.

The first public demo is intentionally sample-driven: it uses real Blender
renders and metadata already generated by the research pipeline.  It exposes
three modes:

* Rule baseline: fast, deterministic geometry screening.
* VLM diagnosis: Qwen2.5-VL with an optional LoRA adapter.
* Hybrid review: rule screening plus VLM explanation and disagreement flag.

Run from the repository root:
    .venv\\Scripts\\python.exe demo\\app.py
"""

from __future__ import annotations

import base64
import html
import json
import mimetypes
import os
import shutil
import subprocess
import sys
import time
import uuid
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from src.data_protocol import build_condition, compact_metadata, read_jsonl
from scripts.run_rule_baseline import infer_defects, infer_severity
from scripts.run_vlm_inference import load_stack, parse_json_object


DEFAULT_MANIFEST = ROOT / "data" / "blender_research_v5_multiasset" / "manifest.jsonl"
DEFAULT_ADAPTER = ROOT / "adapters" / "qwen_b4_blender_v5_fast"
DEFAULT_MODEL = "Qwen/Qwen2.5-VL-3B-Instruct"
REPORT_DIR = ROOT / "demo_reports"
RUNTIME_DIR = ROOT / "runtime_uploads"
BLENDER_CANDIDATES = [
    Path(os.environ.get("PROGRAMFILES", "C:/Program Files")) / "Blender Foundation" / "Blender 5.2" / "blender.exe",
    Path("C:/Program Files/Blender Foundation/Blender 5.2/blender.exe"),
]

_MODEL_CACHE: dict[str, Any] = {}


def _load_gradio():
    try:
        import gradio as gr
    except ImportError as exc:
        raise SystemExit(
            "Missing Gradio. Install the demo dependencies with: "
            ".venv\\Scripts\\python.exe -m pip install -r requirements-demo.txt"
        ) from exc
    return gr


def load_rows(manifest: Path) -> tuple[list[dict[str, Any]], dict[str, dict[str, Any]]]:
    rows = read_jsonl(manifest)
    indexed = {row["id"]: row for row in rows}
    return rows, indexed


def find_blender() -> str:
    for candidate in BLENDER_CANDIDATES:
        if candidate.exists():
            return str(candidate)
    return "blender"


def prepare_uploaded_blend(file_path: str | None, blender_text: str) -> tuple[str, str, dict[str, Any], str, str, str, str]:
    """Convert an uploaded .blend into the same runtime manifest used by samples."""
    if not file_path:
        raise ValueError("Please choose a .blend file first.")
    source = Path(file_path)
    if source.suffix.lower() != ".blend":
        raise ValueError("Only .blend files are supported in Demo v1.")
    blender = blender_text.strip() or find_blender()
    if blender != "blender" and not Path(blender).exists():
        raise ValueError(f"Blender executable not found: {blender}")
    job_dir = RUNTIME_DIR / f"job_{uuid.uuid4().hex[:10]}"
    job_dir.mkdir(parents=True, exist_ok=True)
    copied = job_dir / source.name
    shutil.copy2(source, copied)
    command = [blender, "-b", "-P", str(ROOT / "blender" / "inspect_asset.py"), "--", "--input", str(copied), "--out", str(job_dir), "--views", "4", "--resolution", "256"]
    completed = subprocess.run(command, cwd=str(ROOT), capture_output=True, text=True, timeout=180)
    if completed.returncode != 0:
        tail = (completed.stderr or completed.stdout)[-4000:]
        raise RuntimeError(f"Blender preprocessing failed:\n{tail}")
    manifest = job_dir / "manifest.jsonl"
    if not manifest.exists():
        raise RuntimeError("Blender finished without producing a runtime manifest.")
    rows, indexed = load_rows(manifest)
    row = rows[0]
    paths = resolve_image_paths(row, manifest)
    info = {"source_file": source.name, "runtime_job": str(job_dir), "metadata": compact_metadata(row["metadata"])}
    gr = _load_gradio()
    sample_update = gr.Dropdown(choices=[row["id"]], value=row["id"], label="Test asset")
    return str(manifest), sample_update, info, paths["views"], paths["uv"] or "", paths["normal"] or "", f"Prepared successfully: {source.name}"


def resolve_image_paths(row: dict[str, Any], manifest: Path) -> dict[str, Any]:
    root = manifest.resolve().parent
    images = row.get("images", {})
    views = [str((root / item).resolve()) for item in images.get("views", [])]
    uv = str((root / images["uv"]).resolve()) if images.get("uv") else None
    normal = str((root / images["normal"]).resolve()) if images.get("normal") else None
    return {"views": views, "uv": uv, "normal": normal}


def run_rule(row: dict[str, Any]) -> dict[str, Any]:
    metadata = row.get("metadata", {})
    started = time.perf_counter()
    defects = infer_defects(metadata, uv_threshold=0.001, stretch_ratio=4.0)
    prediction: dict[str, Any] = {
        "quality": "pass" if not defects else "fail",
        "defect_types": defects,
        "severity": infer_severity(defects),
    }
    if row.get("question_type") == "repair_planning":
        repair = {
            "non_manifold": "merge or separate non-manifold components",
            "uv_overlap": "repack overlapping UV islands",
            "flipped_normals": "recalculate and validate face normals",
            "hole": "fill boundary loops and inspect watertightness",
            "stretched_triangles": "rebuild stretched regions with better topology",
            "degenerate_faces": "remove zero-area faces and re-triangulate",
        }
        prediction["repair_plan"] = [repair[name] for name in defects] or ["no repair required"]
    return {
        "prediction": prediction,
        "latency_ms": round((time.perf_counter() - started) * 1000, 2),
        "model": "deterministic_rule_baseline",
        "schema_valid": True,
    }


def normalize_prediction(prediction: dict[str, Any]) -> dict[str, Any]:
    """Repair common schema-key variants without changing semantic values."""
    if not isinstance(prediction, dict):
        return {"_raw": prediction}
    normalized = dict(prediction)
    for source, target in (("repair_plan[]", "repair_plan"), ("defect_types[]", "defect_types")):
        if target not in normalized and source in normalized:
            normalized[target] = normalized.pop(source)
    return normalized


def validate_prediction(prediction: dict[str, Any]) -> tuple[bool, list[str]]:
    errors: list[str] = []
    if prediction.get("quality") not in {"pass", "fail"}:
        errors.append("quality must be pass or fail")
    if prediction.get("severity") not in {"none", "low", "medium", "high"}:
        errors.append("severity is invalid")
    defects = prediction.get("defect_types")
    allowed = {"non_manifold", "uv_overlap", "flipped_normals", "hole", "stretched_triangles", "degenerate_faces"}
    if not isinstance(defects, list) or not all(item in allowed for item in defects):
        errors.append("defect_types must be a list of known defect names")
    if "repair_plan" in prediction and not isinstance(prediction["repair_plan"], list):
        errors.append("repair_plan must be a list")
    return not errors, errors


def get_vlm(row: dict[str, Any], manifest: Path, condition: str, model_id: str, adapter: Path | None,
            min_pixels: int, max_pixels: int, max_new_tokens: int, offload_dir: Path) -> dict[str, Any]:
    cache_key = "|".join([model_id, str(adapter or ""), str(min_pixels), str(max_pixels), str(offload_dir)])
    if cache_key not in _MODEL_CACHE:
        model, processor = load_stack(
            model_id,
            adapter,
            min_pixels,
            max_pixels,
            load_in_4bit=True,
            offload_dir=offload_dir,
        )
        _MODEL_CACHE[cache_key] = (model, processor)
    model, processor = _MODEL_CACHE[cache_key]

    try:
        import torch
        from qwen_vl_utils import process_vision_info
    except ImportError as exc:
        raise RuntimeError("VLM mode requires torch and qwen-vl-utils.") from exc

    payload = build_condition(row, condition, manifest)
    content = [{"type": "image", "image": path} for path in payload["image_paths"]]
    content.append({"type": "text", "text": payload["prompt"]})
    messages = [{"role": "user", "content": content}]
    prompt = processor.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)
    image_inputs, video_inputs = process_vision_info(messages)
    inputs = processor(text=[prompt], images=image_inputs, videos=video_inputs, padding=True, return_tensors="pt").to(model.device)
    started = time.perf_counter()
    with torch.inference_mode():
        generated_ids = model.generate(**inputs, max_new_tokens=max_new_tokens, do_sample=False)
    trimmed = [out_ids[len(in_ids):] for in_ids, out_ids in zip(inputs.input_ids, generated_ids)]
    raw = processor.batch_decode(trimmed, skip_special_tokens=True, clean_up_tokenization_spaces=False)[0]
    prediction = normalize_prediction(parse_json_object(raw))
    valid, errors = validate_prediction(prediction)
    return {
        "prediction": prediction,
        "raw_output": raw,
        "latency_ms": round((time.perf_counter() - started) * 1000, 2),
        "model": model_id,
        "adapter": str(adapter) if adapter else None,
        "schema_valid": valid,
        "schema_errors": errors,
    }


def build_result(row: dict[str, Any], manifest: Path, mode: str, condition: str, model_id: str,
                 adapter_text: str, max_new_tokens: int, min_pixels: int, max_pixels: int,
                 offload_text: str) -> tuple[dict[str, Any], dict[str, Any]]:
    adapter = Path(adapter_text).expanduser() if adapter_text.strip() else None
    if adapter and not adapter.is_absolute():
        adapter = (ROOT / adapter).resolve()
    offload_dir = Path(offload_text).expanduser()
    if not offload_dir.is_absolute():
        offload_dir = (ROOT / offload_dir).resolve()

    rule_result = run_rule(row)
    vlm_result = None
    if mode in {"VLM diagnosis", "Hybrid review"}:
        vlm_result = get_vlm(row, manifest, condition, model_id, adapter, min_pixels, max_pixels, max_new_tokens, offload_dir)

    rule_prediction = rule_result["prediction"]
    vlm_prediction = vlm_result["prediction"] if vlm_result else None
    agreement = None
    review_required = False
    disagreement_reasons: list[str] = []
    if vlm_prediction is not None:
        rule_defects = set(rule_prediction.get("defect_types", []))
        vlm_defects = set(vlm_prediction.get("defect_types", [])) if isinstance(vlm_prediction.get("defect_types"), list) else set()
        agreement = round((len(rule_defects & vlm_defects) / len(rule_defects | vlm_defects)) if rule_defects | vlm_defects else 1.0, 3)
        if rule_defects != vlm_defects:
            disagreement_reasons.append("rule and VLM defect sets differ")
        if rule_prediction["quality"] != vlm_prediction.get("quality"):
            disagreement_reasons.append("rule and VLM quality decisions differ")
        if rule_prediction.get("severity") != vlm_prediction.get("severity"):
            disagreement_reasons.append("rule and VLM severity decisions differ")
        if not vlm_result["schema_valid"]:
            disagreement_reasons.append("VLM output failed schema validation")
        # Safety-first policy: any disagreement is routed to human review.
        review_required = bool(disagreement_reasons)

    if mode == "Rule baseline":
        selected = rule_prediction
        selected_source = "rule_baseline"
    elif mode == "VLM diagnosis":
        selected = vlm_prediction or rule_prediction
        selected_source = "vlm"
    else:
        # Rules remain the hard gate; VLM adds interpretation and repair text.
        selected = dict(rule_prediction)
        if vlm_prediction:
            if vlm_prediction.get("repair_plan"):
                selected["repair_plan"] = vlm_prediction["repair_plan"]
            selected["vlm_quality"] = vlm_prediction.get("quality")
            selected["vlm_defect_types"] = vlm_prediction.get("defect_types", [])
            selected["vlm_severity"] = vlm_prediction.get("severity")
        selected_source = "rule_gate_plus_vlm_explanation"

    result = {
        "asset_id": row.get("scene_id", row.get("id")),
        "sample_id": row["id"],
        "mode": mode,
        "condition": condition,
        "question_type": row.get("question_type"),
        "selected_source": selected_source,
        "selected_result": selected,
        "rule_result": rule_result,
        "vlm_result": vlm_result,
        "agreement_score": agreement,
        "review_required": review_required,
        "disagreement_reasons": disagreement_reasons,
        "metadata": compact_metadata(row.get("metadata", {})),
        "generalization": row.get("generalization"),
    }
    return result, resolve_image_paths(row, manifest)


def _data_uri(path: str | None) -> str:
    if not path or not Path(path).exists():
        return ""
    mime = mimetypes.guess_type(path)[0] or "image/png"
    encoded = base64.b64encode(Path(path).read_bytes()).decode("ascii")
    return f"data:{mime};base64,{encoded}"


def write_report(result: dict[str, Any], paths: dict[str, Any]) -> str:
    REPORT_DIR.mkdir(parents=True, exist_ok=True)
    report_path = REPORT_DIR / f"{result['sample_id']}_{int(time.time())}.html"
    selected = result["selected_result"]
    cards = "".join(
        f'<img src="{_data_uri(path)}" alt="view {idx}" style="width:23%;margin:0.5%;border-radius:8px;">'
        for idx, path in enumerate(paths.get("views", []))
    )
    diagnostics = "".join(
        f'<div style="display:inline-block;width:48%;vertical-align:top;"><h3>{name}</h3><img src="{_data_uri(path)}" style="max-width:100%;border-radius:8px;"></div>'
        for name, path in (("UV layout", paths.get("uv")), ("Normal map", paths.get("normal")))
        if path
    )
    status = "REVIEW REQUIRED" if result["review_required"] else str(selected.get("quality", "unknown")).upper()
    body = f"""<!doctype html><html><head><meta charset='utf-8'><title>3D Quality Report</title>
    <style>body{{font-family:Arial,sans-serif;max-width:1100px;margin:32px auto;padding:0 20px;color:#172033}} .status{{font-size:26px;font-weight:700;padding:18px;border-radius:10px;background:#fff3cd}} pre{{background:#f4f6f8;padding:16px;border-radius:8px;overflow:auto}} </style></head>
    <body><h1>3D Asset Multimodal Quality Report</h1><p><b>Asset:</b> {html.escape(str(result['asset_id']))} &nbsp; <b>Mode:</b> {html.escape(result['mode'])}</p>
    <div class='status'>{html.escape(status)}</div><h2>Selected diagnosis</h2><pre>{html.escape(json.dumps(selected, ensure_ascii=False, indent=2))}</pre>
    <h2>Multi-view evidence</h2><div>{cards}</div><h2>Diagnostic evidence</h2><div>{diagnostics}</div>
    <h2>System details</h2><pre>{html.escape(json.dumps({k:v for k,v in result.items() if k not in {'selected_result','rule_result','vlm_result','metadata'}}, ensure_ascii=False, indent=2))}</pre>
    <h2>Structured metadata</h2><pre>{html.escape(json.dumps(result['metadata'], ensure_ascii=False, indent=2))}</pre></body></html>"""
    report_path.write_text(body, encoding="utf-8")
    return str(report_path)


def make_app():
    gr = _load_gradio()
    manifest_default = str(DEFAULT_MANIFEST if DEFAULT_MANIFEST.exists() else ROOT / "data" / "blender_research_v3" / "manifest.jsonl")
    rows, indexed = load_rows(Path(manifest_default))
    sample_ids = [row["id"] for row in rows if row.get("split") == "test"]
    sample_ids = sample_ids or [row["id"] for row in rows]
    initial = indexed[sample_ids[0]]
    initial_paths = resolve_image_paths(initial, Path(manifest_default))

    def preview(sample_id: str, manifest_text: str):
        manifest = Path(manifest_text).expanduser()
        current_rows, current_indexed = load_rows(manifest)
        row = current_indexed[sample_id]
        paths = resolve_image_paths(row, manifest)
        metadata = compact_metadata(row.get("metadata", {}))
        info = {"id": row["id"], "scene_id": row.get("scene_id"), "split": row.get("split"), "generalization": row.get("generalization"), "question_type": row.get("question_type"), "question": row.get("question"), "metadata": metadata}
        return paths["views"], paths["uv"], paths["normal"], info

    def inspect(sample_id: str, manifest_text: str, mode: str, condition: str, model_id: str,
                adapter_text: str, max_new_tokens: int, min_pixels: int, max_pixels: int, offload_text: str):
        manifest = Path(manifest_text).expanduser()
        _, current_indexed = load_rows(manifest)
        if sample_id not in current_indexed:
            raise ValueError(f"Unknown sample id: {sample_id}")
        result, paths = build_result(current_indexed[sample_id], manifest, mode, condition, model_id, adapter_text, max_new_tokens, min_pixels, max_pixels, offload_text)
        report = write_report(result, paths)
        selected = result["selected_result"]
        summary = {
            "status": "REVIEW REQUIRED" if result["review_required"] else selected.get("quality", "unknown").upper(),
            "defect_types": selected.get("defect_types", []),
            "severity": selected.get("severity", "unknown"),
            "repair_plan": selected.get("repair_plan", []),
            "selected_source": result["selected_source"],
            "agreement_score": result["agreement_score"],
            "review_required": result["review_required"],
            "disagreement_reasons": result["disagreement_reasons"],
        }
        return summary, result, report

    with gr.Blocks(title="3D Asset Multimodal Quality Inspector", theme=gr.themes.Soft()) as demo:
        gr.Markdown("# 3D Asset Multimodal Quality Inspector\n研究型工业质检原型：规则检测负责可靠性，VLM 负责多模态解释与修复建议。")
        with gr.Row():
            with gr.Column(scale=1):
                manifest = gr.Textbox(value=manifest_default, label="Manifest path")
                blender_path = gr.Textbox(value=find_blender(), label="Blender executable")
                asset_upload = gr.File(label="Upload .blend asset", file_types=[".blend"], type="filepath")
                prepare_button = gr.Button("Prepare uploaded asset", variant="secondary")
                upload_status = gr.Markdown("Use an existing sample first, or upload a .blend file for runtime inspection.")
                sample = gr.Dropdown(choices=sample_ids, value=sample_ids[0], label="Test asset")
                mode = gr.Radio(["Rule baseline", "VLM diagnosis", "Hybrid review"], value="Rule baseline", label="Inspection mode")
                condition = gr.Dropdown(["B0", "B1", "B2", "B3", "B4"], value="B4", label="VLM condition")
                model_id = gr.Textbox(value=DEFAULT_MODEL, label="VLM model")
                adapter = gr.Textbox(value=str(DEFAULT_ADAPTER), label="LoRA adapter (optional)")
                with gr.Accordion("GPU controls", open=False):
                    min_pixels = gr.Number(value=50176, precision=0, label="Minimum pixels")
                    max_pixels = gr.Number(value=100352, precision=0, label="Maximum pixels")
                    max_new_tokens = gr.Number(value=128, precision=0, label="Max new tokens")
                    offload = gr.Textbox(value="offload/demo_inference", label="Offload directory")
                inspect_button = gr.Button("Run inspection", variant="primary")
            with gr.Column(scale=2):
                views = gr.Gallery(value=initial_paths["views"], label="Multi-view evidence", columns=4, height="auto")
                with gr.Row():
                    uv = gr.Image(value=initial_paths["uv"], label="UV diagnostic", type="filepath")
                    normal = gr.Image(value=initial_paths["normal"], label="Normal diagnostic", type="filepath")
                asset_info = gr.JSON(value={"id": initial["id"], "scene_id": initial.get("scene_id")}, label="Asset information")
        with gr.Row():
            summary = gr.JSON(label="Inspection result")
            raw_result = gr.JSON(label="Full result / audit record")
        report = gr.File(label="Download HTML report")
        prepare_button.click(
            prepare_uploaded_blend,
            inputs=[asset_upload, blender_path],
            outputs=[manifest, sample, asset_info, views, uv, normal, upload_status],
        )
        sample.change(preview, inputs=[sample, manifest], outputs=[views, uv, normal, asset_info])
        inspect_button.click(inspect, inputs=[sample, manifest, mode, condition, model_id, adapter, max_new_tokens, min_pixels, max_pixels, offload], outputs=[summary, raw_result, report])
    return demo


if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser()
    parser.add_argument("--host", default="127.0.0.1")
    parser.add_argument("--port", type=int, default=7860)
    parser.add_argument("--share", action="store_true")
    args = parser.parse_args()
    make_app().launch(server_name=args.host, server_port=args.port, share=args.share)
